[package]
name = "factory_game"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
tracing = "0.1.41"
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
winit = { version = "0.30.12", features = ["rwh_05"] }
