[package]
name = "factory_game"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
image = "0.25.6"
tracing = "0.1.41"
vulkanalia = { version = "0.32.0", features = ["window"] }
winit = "0.30.12"
